version: "3"

services:

 influxdb:
  container_name: influxdb
  image: influxdb:latest
  volumes:
   - /data/influxdb:/var/lib/influxdb

 grafana:
  container_name: grafana
  image: grafana/grafana:latest
  ports:
   - "3000:3000"
  volumes:
   - /data/grafana:/var/lib/grafana
  links:
   - influxdb

 telegraf:
  container_name: telegraf
  image: telegraf:latest
  volumes:
  - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  links:
  - influxdb

        